name: Validate SVG's & build artifact with PNG's

# Triggers (push, pull request and manual)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Jobs to run
jobs:
  # Validate
  validate_and_build:
    runs-on: ubuntu-latest
    steps:
      # Environment
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      # Dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Generate icons & validate icons
      - name: Validate all icons and metadata
        run: python validate.py

      # Create artifact
      - name: Create artifact
        uses: papeloto/action-zip@v1
        with:
          files: dist/
          dest: icons.zip

      # Get branch
      - name: Extract branch name
        id: release_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      # Get date
      - name: Extract current date
        id: release_date
        shell: bash
        run: echo "::set-output name=datetime::$(date +'%Y-%m-%d %H:%M')"

      # Create release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: tag-${{ steps.release_branch.outputs.branch }}-${{ steps.release_date.outputs.datetime }}
          release_name: Release ${{ steps.release_date.outputs.datetime }}
          draft: false
          prerelease: false

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./icons.zip
          asset_name: icons.zip
          asset_content_type: application/zip