# Validate SVG's & build artifact with PNG's
name: validate

# Triggers for the workflow to run
on:
  # Triggers the workflow on push or pull request events but only for the "master" and "develop" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs to run on trigger
jobs:
  # Validate
  test:
    runs-on: ubuntu-latest
    steps:
      
      # Environment
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      # Dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Generate icons & validate icons
      - name: Validate all icons and metadata
        run: python scripts/validate.py

      # Add 'requirements not met' lable on fail
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ failure() }}
        with:
          labels: 'requirements not met'